name: url-shortener
version: 0.1.0.0
github: "future-stardust/url-shrtnr-haskellxhaskell"
license: GPL-3
author: "Eugene Rossokha, Mark Polaków, Danil Andriushchenko, Helga Korniichuk"
maintainer: "arjaz@protonmail.com, alnyan@protonmail.com, danilandryushenko34@gmail.com, 1704hiolya@gmail.com"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/future-stardust/url-shrtnr-haskellxhaskell>

dependencies:
  - base >= 4.7 && < 5
  - base32
  - random
  - aeson
  - servant-server
  - servant-auth
  - servant-auth-server
  - wai
  - warp
  - text
  - bcrypt
  - bytestring
  - binary
  - time
  - mtl

library:
  source-dirs: src

executables:
  url-shortener-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - url-shortener

tests:
  url-shortener-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - url-shortener
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
